# Generated by Django 2.2.7 on 2019-11-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=254)),
                ('apellido', models.CharField(max_length=254)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=254)),
                ('direccion', models.CharField(max_length=254)),
                ('carrera', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=254)),
            ],
        ),
    ]
